/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://x4qj3wflbbetvd77ouvpdt5ksy.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aewnwkxlxbb55lsatk5rlsv6uy",
    "aws_cognito_identity_pool_id": "eu-west-2:8262dcbb-25ae-4ea3-91ce-072dcd4d960f",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_UBV4ei2Rb",
    "aws_user_pools_web_client_id": "2dijqjatui0eic5qiesd7g8u2k",
    "oauth": {}
};


export default awsmobile;
